# @baseUrl = https://transport-backend-7twe.onrender.com/api
@baseUrl = http://localhost:4000/api

@driverId = 314226f9-ebb8-46ed-90ae-7c481d2f0c72
@userId = 0920dac7-366f-4c81-a8c2-56d478d42fbc
@ticketId = 4
@rideId=4817816e-dd03-43a5-8c72-3b1d2d8f8e11

###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "phone":"03302319144",
  "password":"openplz123",
  "role":"driver"
}
###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "phone":"03302619134",
  "password":"openplz123",
  "role":"user"
}

###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "phone":"03302319144",
  "password":"openplz123"
}
 

###
POST {{baseUrl}}/auth/update-password
Content-Type: application/json  

{
  "userId":"{{userId}}",
  "oldPassword":"openplz123", 
  "newPassword":"newpassword123"
}
###

PUT {{baseUrl}}/user/profile
Content-Type: application/json
Authorization: 

{ 
  "id":"{{userId}}",
  "email": "user@example.com",
  "img_url": "http://image.url/profile.png",
  "location": {
    "address": "Gulshan, Karachi",
    "latitude": 24.8607,
    "longitude": 67.0011
  },
  "full_name": "Maaz Abdul Jabbar"
}


###
PUT {{baseUrl}}/user/profile
Content-Type: application/json
Authorization:

{
  "id": "{{driverId}}",
  "email": "maaz@example.com",
  "img_url": "http://image.url/profile.png",
  "location": {
    "address": "Gulshan, Karachi",
    "latitude": 24.8607,
    "longitude": 67.0011
  },
  "full_name": "Maaz Abdul Jabbar",
  "vehicle_info_url": "http://image.url/vehicle.png",
  "vehicle_number": "ABC-1234",
  "vehicle_model": "Toyota Corolla 2022",
  "license_url": "http://image.url/license.png",
  "license_number": "DL-987654321",
  "license_valid": "2026-12-31",
  "vehicleType": "bike",              
  "vehicleLimit": 4                  
}

###
GET {{baseUrl}}/user/drivers
###
GET {{baseUrl}}/user/user/{{userId}}
###
PUT {{baseUrl}}/user/driver/verify/{{driverId}}
Content-Type: application/json  

{
  "status": "verified"
}



###
POST {{baseUrl}}/rides/register-ride
Content-Type: application/json
Authorization:


{
  "userId": "{{userId}}",       
  "pickup": {
    "address": "huddinmsmsm, Karachi",
    "latitude": 24.8607,
    "longitude": 67.0011
  },
  "destination": {
    "address": "saddr, Karachi",
    "latitude": 24.8046,
    "longitude": 67.0369
  },
  "price": 1500,
  "rideDatetime": "2025-07-01T14:00:00Z",
  "durationDays": 1,
  "requiredVehicleType": "car"  ,
  "time": "14:00:00"
}

###
GET {{baseUrl}}/rides/get-rides-driver/{{driverId}}
###

GET {{baseUrl}}/rides/get-ride/{{userId}}

###
POST  {{baseUrl}}/rides/acceptRide
Content-Type: application/json
Authorization:

{
  "driverId": "{{driverId}}",
  "rideId": "{{rideId}}"
}

###
PUT  {{baseUrl}}/rides/status/{{rideId}}
Content-Type: application/json
Authorization:

{
  "newStatus": "completed "
}
###
GET {{baseUrl}}/rides/all-rides
###
GET {{baseUrl}}/rides/rideById/{{rideId}}
###
POST  {{baseUrl}}/reviews
Content-Type: application/json  
Authorization:

{
  "userId": "{{userId}}",
  "rideId": "{{rideId}}",
  "rating": 5,
  "comment": "Smooth ride and professional dr253e4903-3fef-417b-ada5-442adff0acd3iver"
}



###
POST   {{baseUrl}}/notification/send
Content-Type: application/json
Authorization:

{
  "title": "cancelled",
  "message": "Your ride has been cancelled.",
  "user_id": "{{userId}}",  

}


### Variables




### Create Ticket
POST {{baseUrl}}/tickets
Content-Type: application/json

{
  "title": "Login Issue",
  "description": "Unable to log into account after password reset.",
  "priority": "high",
  "userId": "{{userId}}"
}


### Get All Tickets
GET {{baseUrl}}/tickets
Content-Type: application/json


### Get Ticket by ID
GET {{baseUrl}}/tickets/4
Content-Type: application/json


### Update Ticket (full update)
PUT {{baseUrl}}/tickets/{{ticketId}}
Content-Type: application/json

{
  "title": "Updated Ticket Title",
  "description": "Updated description of the issue.",
  "priority": "low"
}



### Change Ticket Status
PATCH {{baseUrl}}/tickets/{{ticketId}}/status
Content-Type: application/json

{
  "status": "closed"
}



### Add Message to Ticket
POST {{baseUrl}}/tickets/message
Content-Type: application/json

{
  "ticketId": "{{ticketId}}",
  "senderType": "admin",
  "message": "Any update on this issue?"
}


###
GET {{baseUrl}}/tickets/{{ticketId}}/messages






